services:
  app:
    build:
      context: .
      args:
        NEW_UID: ${NEW_UID:-1000}
        NEW_GID: ${NEW_GID:-1000}
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/src
      - ./secrets:/src/secrets
    ports:
      - 8501:8501
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/health"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      - localisation_db
    networks:
      zmodules:
        aliases:
          - localization-app

  app_ssl:
    image: httpd
    restart: "no"
    ports:
      - "8541:443"
    volumes:
      - "./secrets:/usr/local/secrets"
      - "./docker/httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./docker/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf"
    depends_on:
      app:
        condition: service_healthy
    networks:
      zmodules:
        aliases:
          - localization

  localisation_db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5401:5432
    networks:
      - zmodules

networks:
  zmodules:
    driver: bridge
    name: zmodules

volumes:
  secrets:
    name: secrets2
