version: "3"

services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        volumes:
            - ./:/src
        ports:
            - 8502:8502
        networks:
            - zmodules

    localisation_db:
        image: postgres:14
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        networks:
            - zmodules

networks:
  zmodules:
    driver: bridge
