version: "3.5"

services:
    app:
        build:
            context: .
            args:
                NEW_UID: ${NEW_UID:-1000}
                NEW_GID: ${NEW_GID:-1000}
        volumes:
            - ./:/src
        ports:
            - 8501:8501
        networks:
            zmodules:
                aliases:
                    - localisation

    localisation_db:
        image: postgres:14
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        ports:
            - 5401:5432
        networks:
            - zmodules

networks:
  zmodules:
    driver: bridge
    name: zmodules
