@startuml
!include <C4/C4_Container>

Person(professional, "Healthcare Professional")
System(healthcareSystem, "epd", "Or other healthcare systems")
System(nationalReferralIndex, "National Referral Index", "Nationale Verwijsindex")

Rel(professional, healthcareSystem, "Request timeline")
Rel(healthcareSystem, nationalReferralIndex, "Lookup referrals")

@enduml
